##############################################
### Concourse Objects
##############################################

##############################################
### PCF Object Params
##############################################
opsman_major_minor_version: '1\.12\..*' # Reqd
ert_major_minor_version: '1\.12\..*' # Reqd

# Pivent Download token
pivnet_token: zme9W-ocgfkgiLdwyZGr

# ERT Domain Name
pcf_ert_domain: mag.perfexel.com # This is the domain you will access ERT with
system_domain: sys.${pcf_ert_domain} # This is usually sys.${pcf_ert_domain}
apps_domain: cfapps.${pcf_ert_domain} # This is usually cfapps.${pcf_ert_domain}
pcf_ssh_key_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF0GDMx3qQtljwIAELV4cITOzvjRZAanQq6c8wPhzKWcnrQmu3PMUNg9zbzfwJAJcksG9pn0Z/srvJW/GEQHVgVjrW7EGoXWeqYzWP0nO6RacgCXclxOkTeP/MchYnEhI5gjVIGzDqZ0hgSwU4wc4m37wl22KH6sM5W6izLqihZzBu2NNnzNn8nLGTIIj/pvr/DDfFXIPbZcgD0eJTy72wRbHnb/Ykd2WIFwQfxqUp5Q7mbbU80ITJzDWJF6yVxbOarnCyR0DpBdBObF2cOXi3soZLmshXrCO5tK8rmMY4x6Bpqtr/XqRkpvUA6A/koqHWYZxyflObNxFUmbgj9o5N ubuntu"
pcf_ssh_key_priv: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAxdBgzMd6kLZY8CABC1eHCEzs740WQGp0KunPMD4cylnJ60Jr
  tzzFDYPc2838CQCXJLBvaZ9Gf7K7yVvxhEB1YFY61uxBqF1nqmM1j9JzukWnIAl3
  JcTpE3j/zHIWJxISOYI1SBsw6mdIYEsFOMHOJt+8Jdtih+rDOVuosy6ooWcwbtjT
  Z8zZ/JyxkyCI/6b6/ww3xVyD22XIA9HiU8u9sEWx52/2JHdliBcEH8alKeUO5m21
  PNCEycw1iReslcWzmq5wskdA6QXQTmxdnDl4t7KGS5rIV6wjubSvK5jGOMegaara
  /16kZKb1AOgP5KKh1mGccn5TmzcRVJm4I/aOTQIDAQABAoIBAQCwD4k4egsSpdl+
  z11elOawcpcnlvFJH/aJA1TO4VmKmGPpKlLo4gOYxdZbJHjAInBjzU08OvDqU1Bk
  JZtOVHij59uy0tCVY50Sv/46Jduu3LOlBgev7BRuqnExrBEfcSwbV1LI/LqKxqZa
  Xislmwk6/ENfhmWqBz7+3B/IayzXiYi7mNDWCbU6oV2DVLjQwfS0BL3q5JhL6wjS
  HbwRvEplcald2rquQzpm3U/UBTKiC2BJgvCPwHsYVlJIAex7D+Qs1EjlmaysBQY5
  sErpHdoxWcmX2ZNLWi9N5Jefx9UOA+kDzPtLy875hEc/Xg6zChL7mMRZik8Q38XV
  v/z8HBGZAoGBAPE5wXaqTWaceVL07xs4Nefp5zHQtGhXDIuDrGRTWF2GoEvpzl14
  Z8Hp06bB+o59VaFAnR83YKniW1WRJaptyClpi8Ih1uK7IrrsYp7MCM4UfBSydHRK
  tekr0pFNxop/P9eC16moVxNsyn7l/B9uvf0ABKd0KhsnnjwvL6sHRCebAoGBANHt
  9Y7CoWEm04lKsvf6AZ5OD7GhZgGw3ymSJ97AVBLwKTnt2T6J9dj1pVZ2GReL302s
  9pNJ0akhmGpa/ctumtspnGuVH6o/Zlfllhsl20fZQbgIGlDDg0YYs8FZNgFPZ4o7
  BSi3hrCEnS4RjxbOI+MAiDInnbsKR3XyJ1IB5OQ3AoGBAJ/p/9zg7UrW9H8QLOrI
  isPhhgi6KL765jAe7EveDLiDpQRuTQYd6frdPhhQg/+uCvRJV1/4YDZ+/rls7aFc
  AdOiSqo5sLDCCjYMuxw2eqfTYKZ/3z+wv4OCL6dv/eyWiwYdkUbBeGhCOMODR263
  BXARcQRpt/gkfXu8dEdXG9F9AoGADwXqdsby6ZLvvHl+CUT47K1Fbj7Qn/paXg05
  kTVOTvSk3qJo05Ln5xjdNizJauf1mQdxteSofmQLFkFgvDg0GM8HhKNtWq+i0VN6
  xIKXCLNBgrwBthnnwRJvery5oqpeDIRgwCMyHlu/K9bR2J3z74DQPlabcRExP/2O
  Vs4P5U0CgYA02GjFAuIupUhtwADDnxze7uk7AQDzIwTWTP8Y6ZodLf72BI04P2nD
  PAFH+elSpfwPSJ9smVe0Y7krFGFnJA7gOsdtwYWXh2JivysltWx5ksWIO5euTNLS
  38B4/+vlHnD55qEclec/VYcw2X+AWSPiXCL9C/r6Z3nftFh9hRpjMw==
  -----END RSA PRIVATE KEY-----


# Opsman Settings
opsman_domain_or_ip_address: opsman.mag.perfexel.com # This should be your pcf_ert_domain with "opsman." as a prefix
opsman_admin_username: admin
opsman_admin_password: password

haproxy_forward_tls: disable # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca:         # HAProxy will use the CA provided to verify the certificates provided by the router.

# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
router_tls_ciphers: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384        # The recommended setting is "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".
haproxy_tls_ciphers: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384        # The recommended setting is "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".

# ERT Cert & Key, if the string is blank, then the pipeline will auto generate certs
pcf_ert_ssl_cert:
pcf_ert_ssl_key:

trusted_certificates: # Trusted certificates to be deployed along with all VM's provisioned by BOSH

# SAML Service Credential provider Cert and Key, if the string is blank, then the pipeline will auto generate certs
pcf_ert_saml_cert:
pcf_ert_saml_key:

##############################################
### IaaS Specific Params
##############################################
# Wipe Arg(s) anything other than wipe bypasses the wipe-env job
arg_wipe: wipe

# The storage account and container that will be used for your terraform state
terraform_azure_account_name: consan
terraform_azure_access_key: "f1BNVsiGMw5kM5OtyUGXuaaNu2/z7qTGfu9D4UJTDp9mrCGgcXhNAyvbcCXQIZsi8ZRjVVSARaklu5RLfl7tqA=="
azure_storage_container_name: terraformstate

### azure ###
# IF the azure_access_name is empty "", ERT will use internal storage. If you want ERT to use Azure blob store, provide a valid azure_account_name and azure_account_key values.
azure_account_name:

# REQD if Azure blob storage is used as external storage by ERT, which is determined by azure_access_name being not null. This setting is used to specify the container where the buildpacks will be stored. It is similar to the S3 bucket in AWS.
azure_buildpacks_container:

# REQD if Azure blob storage is used as external storage by ERT, which is determined by azure_access_name being not null. This setting is used to specify the container where the droplets will be stored. It is similar to the S3 bucket in AWS.
azure_droplets_container:

# REQD if Azure blob storage is used as external storage by ERT, which is determined by azure_access_name being not null. This setting is used to specify the container where the packages will be stored. It is similar to the S3 bucket in AWS.
azure_packages_container:

# REQD if Azure blob storage is used as external storage by ERT, which is determined by azure_access_name being not null. This setting is used to specify the container where the resources will be stored. It is similar to the S3 bucket in AWS.
azure_resources_container:

azure_multi_resgroup_network:
azure_multi_resgroup_pcf:
azure_multi_resgroup_infra_subnet_name:
azure_multi_resgroup_infra_vnet_name:

azure_pcf_terraform_template: c0-azure-base # 'Template' for pipeline to determine Terrafrom & Opsman JSON config
azure_subscription_id: "198a21b4-8e7b-4bc8-8ae2-c27aedae1e5e" # REQD
azure_tenant_id: "e88daabc-6008-4c03-beec-1d3fd6473027" # REQD
azure_region: usgovvirginia # valid Azure region reqd
azure_environment: AzureUSGovernment # valid Azure environment reqd
azure_client_id: "9032c588-21f8-4970-adfa-912d52d13f55"
azure_client_secret: "keepitsimple"
azure_terraform_prefix: "conpcf"
azure_terraform_subnet_dynamic_services_cidr: "192.168.12.0/22"
azure_terraform_subnet_dynamic_services_dns: "168.63.129.16,8.8.8.8"
azure_terraform_subnet_dynamic_services_gateway: "192.168.12.1"
azure_terraform_subnet_dynamic_services_reserved: "192.168.12.1-192.168.12.9"
azure_terraform_subnet_ert_cidr: "192.168.4.0/22"
azure_terraform_subnet_ert_dns: "168.63.129.16,8.8.8.8"
azure_terraform_subnet_ert_gateway: "192.168.4.1"
azure_terraform_subnet_ert_reserved: "192.168.4.1-192.168.4.9"
azure_terraform_subnet_infra_cidr: "192.168.0.0/26"
azure_terraform_subnet_infra_dns: "168.63.129.16,8.8.8.8"
azure_terraform_subnet_infra_gateway: "192.168.0.1"
azure_terraform_subnet_infra_reserved: "192.168.0.1-192.168.0.9"
azure_terraform_subnet_services1_cidr: "192.168.8.0/22"
azure_terraform_subnet_services1_dns: "168.63.129.16,8.8.8.8"
azure_terraform_subnet_services1_gateway: "192.168.8.1"
azure_terraform_subnet_services1_reserved: "192.168.8.1-192.168.8.9"
azure_terraform_vnet_cidr: "192.168.0.0/20"
pcf_opsman_disk_size_in_gb: 120

container_networking_nw_cidr: 10.255.0.0/16 # c2c networking network cidr

# azure_vm_admin value should match with userid used to create the certs pcf_ssh_key_pub. The userid will appear towards the end of the pub key
azure_vm_admin: ubuntu
azure_vm_password:

mysql_monitor_recipient_email:  # Email address for sending mysql monitor notifications
mysql_backups: disable   # Whether to enable MySQL backups. (disable|s3|scp)

#SCP backup config params (leave empty values if you're not using scp
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

## These resources can take any parameter made available in
## the ops manager API ( https://your-ops-man/docs#configuring-resources-for-a-job )
nats_instances: 2
nfs_server_instances: 1
mysql_proxy_instances: 1
mysql_instances: 1
backup_prepare_instances: 0
uaa_instances: 2
cloud_controller_instances: 2
ha_proxy_instances: 1
mysql_monitor_instances: 0
clock_global_instances: 1
cloud_controller_worker_instances: 2
consul_server_instances: 3
diego_database_instances: 3
router_instances: 3
diego_brain_instances: 3
diego_cell_instances: 3
loggregator_traffic_controller_instances: 3
syslog_adapter_instances: 3
doppler_instances: 3
tcp_router_instances: 0

internet_connected: false

deployment_network_name: "ert"
enable_security_event_logging: true
syslog_host:
syslog_port:
syslog_protocol:
syslog_drain_buffer_size:
company_name: perfexel
authentication_mode: internal
loggregator_endpoint_port:
disable_http_proxy:
tcp_routing: disable
tcp_routing_ports:
route_services: enable
ignore_ssl_cert_verification: true
smtp_from:
smtp_address:
smtp_port:
smtp_user:
smtp_pwd:
smtp_auth_mechanism:
security_acknowledgement: "X" # Change to 'X'
default_quota_memory_limit_mb: 10240
default_quota_max_number_services: 1000
ha_proxy_ips: 192.168.4.100,192.168.4.101
skip_cert_verify: true
disable_insecure_cookies: false
router_static_ips:
router_request_timeout_in_seconds: 900
garden_network_pool_cidr: 10.254.0.0/22 # Only change this if you need to avoid address collision with a third-party service on the same subnet.
garden_network_mtu: 1454
allow_app_ssh_access: false
tcp_router_static_ips:
ssh_static_ips:
ha_proxy_lb_name: con-pcf-lb
